databases:
  - name: myKirokun_DB
    databaseName: mykirokun_db
    user: MyKirokun_API
    region: singapore

services:
  - type: pserv
    name: redis
    env: docker
    autoDeploy: false
    disk:
      name: data
      mountPath: /var/lib/redis
      sizeGB: 10
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: myKirokun_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        fromService:
          name: myKirokun_DB
          type: redis
          property: connectionString
        sync: false
    autoDeploy: false

    - type: redis
    name: myKirokun_DB
    region: singapore
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

databases:
  - name: myKirokun_DB
    region: singapore
    ipAllowList: []
